name: Deploy FastAPI with Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Start FastAPI Server
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &

      - name: Restart Nginx (Windows)
        run: |
          taskkill /F /IM nginx.exe || echo "Nginx not running"
          start C:\nginx\nginx.exe
        shell: cmd
